### ISSUE TITLE
ERROR: Wong CRC on register 0x60!Quering register 0x61...

### ISSUE THREAD

**Issue by leonidnf** [raomin/ESPAltherma#165] opened 2022-10-13 21:12 UTC
Hi, community!
first of all, thank you @raomin, and contributors for the project! It's lovely to have such a tool for controlling and monitoring our heating/cooling device!

I have a slight problem with connecting my M5stickplus to the HPSU and I hope that I'll get a little help.

I'm getting the following error  on the M5stickplus LCD:
ERROR: Wong CRC on register 0x60!Querying register 0x61...

The interesting part is that I'm receiving values in MQTT Broker, for all uncommented lines. For testing purpose, I left only one uncommented line `DHW tank temp. (R5T)`. Below is the payload from Home Assistant MQTT:

`QoS: 0
Payload: [
  {
    "DHW tank temp. (R5T)": 40.2,
    "M5VIN": "4.4V",
    "M5AmpIn": "104.375mA",
    "M5BatV": "4.12V",
    "M5BatCur": "0mA",
    "M5BatPwr": "0mW",
    "WifiRSSI": "-26dBm"
  }
]`

Here is my setup:
HPSU: EHSXB08P50DA3

Uncommented `HPSU6_ULTRA` and no custom code added to the project.
Already checked the ground cable (and changed it with the other two) and connected it to the metal case of HPSU the problem still persists. 
When the ground cable is removed, I'm getting another error.
![20221013_222156 (1)](https://user-images.githubusercontent.com/39941600/195711564-6eb3db27-4811-49c9-b4f7-42a3cddcf3f9.jpg)
![20221013_222310](https://user-images.githubusercontent.com/39941600/195711611-a8927a83-fafa-4ae7-9d5d-798b849a6aec.jpg)
![20221013_222131](https://user-images.githubusercontent.com/39941600/195711632-cfaff293-0714-4ecd-8c91-e2bb8e06a7d7.jpg)
![20221013_222126 (1)](https://user-images.githubusercontent.com/39941600/195711634-fcdc3358-585e-4f25-9f4c-f480aa9e8f89.jpg)

**Comment by TomOudeNijhuis** [comment] 2022-10-16 14:45
I had the same issue and switched back to an older version. After some experimenting I think that pull request #149 broke things. 

Have tried to find the exact source of the issue, but no luck yet. Must say that mixing the protocols in `comm.h` has not made the code easier to read. There is some mixed usage of `unsigned char`, `char` and `uint8_t` as well, but fixing this did not resolve the issue.

**Comment by raomin** [comment] 2022-10-16 15:20
Thanks @TomOudeNijhuis for the feedback. I'll have a deeper look and report here.

**Comment by agrenott** [comment] 2022-10-16 22:12
Hi @TomOudeNijhuis , could you please un-comment the logBuffer(buffer, len); on line 118 of comm.h (right before the get CRC) and post the resulting logs?

**Comment by raomin** [comment] 2022-10-16 22:49
From the picture, looks like it's for 0x60 and 0x61 
I haven't tested #149, I will tomorrow, but my understanding is that `unsigned char` or `char` shouldn't change anything.

**Comment by raomin** [comment] 2022-10-16 23:15
Actually, you're not the only one reporting some CRC errors while still having some values properly reported.
This intermittent issues could either be caused by a faulty cabling or, if this is fixed by reverting to a previous commit before #149, then it might be the change introduced by the `Serial.flush()`.
For this one, @agrenott was right to add the parameter to false as it is intended to make sure we do not have ghost values on the input before sending our queries, so I don't think it's this.

Now if @TomOudeNijhuis reverted before #128, this could be because of the removal of the wait time between registries queries... [(here](https://github.com/raomin/ESPAltherma/commit/840378a49357c3da59c10d116af61399a01484b1#diff-34d21af3c614ea3cee120df276c9c4ae95053830d7f1d3deaf009a4625409ad2L257)
I really need to do some more testing....

**Comment by andreapier** [comment] 2022-10-17 06:25
This is happening to me too. Can confirm this only happens with registers `0x60` and `0x61`. Other registers work fine.
I double checked my wiring just in case, but it looks to be just fine.
Let me know if you need more info, thanks.

**Comment by agrenott** [comment] 2022-10-17 06:55
I guess this is indeed linked to the unsigned vs. signed mix-up, as the equality isn't verified for values > 127:
https://onlinegdb.com/S3x5e2t9_
![image](https://user-images.githubusercontent.com/12431371/196108912-b8ed0547-a386-45d4-8d19-a7d29994a0c9.png)

I can't reproduce, but I'll submit a PR.

**Comment by leonidnf** [comment] 2022-10-17 10:29
Hi @raomin, @agrenott, @TomOudeNijhuis,
I've just tested the `Fix CRC computation` PR on my system and the error still persists.
Also, I've checked out a commit before #149 and it works without errors.

Please let me know if I can help you with something

**Comment by agrenott** [comment] 2022-10-17 11:06
Hi @leonidnf , sad my change doesn't fix the issue.
Can you please uncomment the logBuffer line and attach the failing case?
https://github.com/raomin/ESPAltherma/blob/main/include/comm.h#L118

You can fetch it from the MQTT log topic, or the serial console if you connect to it with USB cable.

**Comment by agrenott** [comment] 2022-10-17 11:26
I've just pushed a 2nd commit with a bug fix which is so obvious I can't understand how only 0x60+ register would be impacted, as I basically truncated all protocol I replies by 2 bytes...
@leonidnf if you can test it please.

**Comment by leonidnf** [comment] 2022-10-17 11:47
@agrenott Thank you for the fast reply and for solving the issue!
I'm happy to confirm that the bug is in the past! Now I see clean logs

**Comment by raomin** [comment] 2022-10-17 20:47
Seen the PR, looks good now, thanks @agrenott! I'm merging.

**Closed by raomin** 2022-10-17 20:47 UTC
