### ISSUE TITLE
WiFi connection on Mesh WiFi system

### ISSUE THREAD

**Issue by TommasoPino** [raomin/ESPAltherma#213] opened 2022-12-19 13:51 UTC
Hi everyone, I am experiencing inconvenient behavior where the device that is connected with a high signal, for some reason, reset the wifi connection and it switches on a station that has a very low signal. I do not understand why it prefers to connect to a station of the mesh with a low signal, I think the reason is that there is no order to which station connects.

I have no time or experience in modifying the code, but hypothetically speaking using a library like this [https://randomnerdtutorials.com/esp32-wifimulti/](https://randomnerdtutorials.com/esp32-wifimulti/) could the problem be solved?

Thanks in advance for your time.

**Comment by raomin** [comment] 2022-12-20 23:17
I experience this too. The esp32 seems to randomly select the AP.
In my case both AP broadcast the same SSID so wifimulti would not help.
However, it seems that the problem is identified and is being fixed in esp-idf: https://github.com/espressif/esp-idf/issues/8269
(BTW it seems it's more an authentication failure (it can happen) on the best AP that make it end up on the worst).

Hopefully, it will solve this issue soon. 
Nothing related to ESPAltherma but I'll keep an eye on this to see if some code change is needed.

**Comment by raomin** [comment] 2023-04-04 17:23
I just pushed a commit that should fix this... 🤞

**Closed** 2024-01-05 00:50 UTC
